#### NUMPY


In [99]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
lis=["A","B",24,45.678,3+5j,True]

In [5]:
lis

['A', 'B', 24, 45.678, (3+5j), True]

In [6]:
type(lis)

list

In [7]:
#Numpy stores data in numpy array

In [8]:
#Numpy array is homogenous 
# It can only store integer,float,string

In [10]:
l=[1,2,3,4,5]
arr=np.array(l)

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
l=[1,2,3,4,"Aman"]

In [14]:
np.array(l)

array(['1', '2', '3', '4', 'Aman'], dtype='<U11')

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr.ndim

1

In [17]:
arr1=np.array([[2,3,4,5],[6,7,8,9]])

In [18]:
arr1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [19]:
arr1.ndim

2

In [20]:
arr_t=np.array([[2]])

In [21]:
arr_t

array([[2]])

In [23]:
arr_t.ndim

2

In [24]:
mat=np.matrix([1,2,3,4,5])

In [25]:
mat

matrix([[1, 2, 3, 4, 5]])

In [26]:
mat.ndim

2

In [27]:
type(mat)

numpy.matrix

In [28]:
arr3=np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [29]:
arr3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [33]:
arr3.ndim

3

In [34]:
t=([1,2,3,4],[5,6,7,8])

In [35]:
type(t)

tuple

In [39]:
arr4=np.array(t)

In [40]:
arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
arr[0]

1

In [44]:
arr4[0][3]

4

In [45]:
arr

array([1, 2, 3, 4, 5])

In [46]:
arr[2]

3

In [47]:
arr[2]=200

In [48]:
arr

array([  1,   2, 200,   4,   5])

In [49]:
a=arr

In [50]:
a[0]

1

In [51]:
arr[0]

1

In [53]:
a[0]=100

In [54]:
a

array([100,   2, 200,   4,   5])

In [55]:
arr

array([100,   2, 200,   4,   5])

In [56]:
b=arr.copy()

In [57]:
b

array([100,   2, 200,   4,   5])

In [58]:
arr

array([100,   2, 200,   4,   5])

In [59]:
b[1]=24

In [60]:
b

array([100,  24, 200,   4,   5])

In [61]:
arr

array([100,   2, 200,   4,   5])

In [62]:
arr5=np.fromfunction(lambda i,j : i==j,(3,3))

In [63]:
arr5

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [64]:
def sum(i,j):
    return i+j

arr6=np.fromfunction(sum,(3,4))

In [65]:
arr6

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [66]:
arr6.ndim

2

In [67]:
arr6.shape

(3, 4)

In [68]:
arr6.size

12

In [70]:
for i in range (5):
    print(i)


0
1
2
3
4


In [73]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [74]:
(i for i in range(5))

<generator object <genexpr> at 0x000001AD6C730580>

In [75]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [76]:
iterator = (i for i in range(5))

In [77]:
iterator

<generator object <genexpr> at 0x000001AD6C730700>

In [79]:
next(iterator)

0

In [80]:
np.fromiter(iterator,int)

array([1, 2, 3, 4])

In [86]:
np.fromstring('2 3 4', sep=" ")

array([2., 3., 4.])

In [87]:
np.fromstring('5 6 7', sep=" ", dtype=int)

array([5, 6, 7])

In [89]:
string = "Ajay Bijay Sanjay"
string.split(" ")

['Ajay', 'Bijay', 'Sanjay']

In [91]:
np.array(string.split(" "))

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [92]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [94]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [98]:
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])