In [1]:
import numpy as np

In [2]:
a=np.zeros(5)

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
a.shape

(5,)

In [6]:
b=np.zeros(10,dtype=int)

In [7]:
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
c=np.zeros((3,4),dtype=int)

In [9]:
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
c.ndim

2

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
t=np.array([[2,2,2],[2,2,2]])

In [15]:
t

array([[2, 2, 2],
       [2, 2, 2]])

In [16]:
t.ndim

2

In [17]:
t.shape

(2, 3)

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr=np.zeros((3,3,4))

In [22]:
arr.ndim

3

In [23]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
arr=np.zeros((3,4))

In [25]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [28]:
arr*2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
import random 

In [33]:
random.choice((1,2,3,3,4))

2

In [34]:
random.randrange(1,10)

6

In [35]:
random.random()

0.5191831471369699

In [36]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [37]:
random.shuffle(lis)

In [38]:
lis

[1, 5, 3, 2, 4]

In [39]:
random.uniform(7,14)

13.927635395171727

In [40]:
np.array([])

array([], dtype=float64)

In [41]:
np.random.random_sample()

0.06599617290563486

In [42]:
np.random.random_sample(5)

array([0.35932829, 0.32834484, 0.072827  , 0.40489191, 0.84622591])

In [45]:
np.random.random_sample((4,2))

array([[0.70765746, 0.40205634],
       [0.87287759, 0.87503012],
       [0.17009481, 0.67119457],
       [0.74031869, 0.99184363]])

In [46]:
np.random.rand(1)

array([0.39147793])

In [48]:
np.random.rand(2,3)

array([[0.28146953, 0.15412431, 0.29770045],
       [0.75191133, 0.66683717, 0.7129005 ]])

In [54]:
arr=np.random.randint(1,5,size=(3,4))

In [55]:
arr.ndim

2

In [56]:
arr.shape

(3, 4)

In [57]:
arr1=arr.reshape(2,6)

In [58]:
arr1

array([[2, 3, 3, 4, 4, 4],
       [3, 2, 2, 3, 4, 1]])

In [59]:
#In case I don't know about the row or column

In [60]:
arr.reshape(4,-1)

array([[2, 3, 3],
       [4, 4, 4],
       [3, 2, 2],
       [3, 4, 1]])

In [61]:
arr.reshape(2,-100)

array([[2, 3, 3, 4, 4, 4],
       [3, 2, 2, 3, 4, 1]])

In [62]:
arr.reshape(-100,3)

array([[2, 3, 3],
       [4, 4, 4],
       [3, 2, 2],
       [3, 4, 1]])

In [63]:
arr

array([[2, 3, 3, 4],
       [4, 4, 3, 2],
       [2, 3, 4, 1]])

In [64]:
arr.reshape(12,1)

array([[2],
       [3],
       [3],
       [4],
       [4],
       [4],
       [3],
       [2],
       [2],
       [3],
       [4],
       [1]])

In [65]:
arr.reshape(12,1).base

array([[2, 3, 3, 4],
       [4, 4, 3, 2],
       [2, 3, 4, 1]])

In [66]:
arr.reshape(2,3,2)

array([[[2, 3],
        [3, 4],
        [4, 4]],

       [[3, 2],
        [2, 3],
        [4, 1]]])

In [72]:
arr1=np.random.randint(1,6,(4,5))

In [73]:
arr1

array([[2, 2, 3, 4, 5],
       [5, 5, 1, 4, 1],
       [4, 4, 1, 2, 4],
       [4, 4, 1, 5, 5]])

In [74]:
arr1.shape

(4, 5)

In [76]:
arr1>3

array([[False, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [ True,  True, False,  True,  True]])

In [77]:
arr1[arr1>3]

array([4, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5, 5])

In [78]:
#accessing element in array

In [80]:
arr1[0]

array([2, 2, 3, 4, 5])

In [81]:
arr1[0][0]

2

In [84]:
#from 0th row to 2nd row
arr1[0:3]

array([[2, 2, 3, 4, 5],
       [5, 5, 1, 4, 1],
       [4, 4, 1, 2, 4]])

In [87]:
arr1

array([[2, 2, 3, 4, 5],
       [5, 5, 1, 4, 1],
       [4, 4, 1, 2, 4],
       [4, 4, 1, 5, 5]])

In [86]:
#from xth row to yth row and nth column to mth column
arr1[0:3,0:3]

array([[2, 2, 3],
       [5, 5, 1],
       [4, 4, 1]])

In [88]:
#from oth row to 2nd row and 0th and 2nd column
arr1[0:3,[0,2]]

array([[2, 3],
       [5, 1],
       [4, 1]])

In [89]:
#MATHEMATICAL OPERATIONS ON ARRAYS

In [95]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [96]:
arr1

array([[2, 2, 2],
       [2, 1, 2],
       [1, 1, 1]])

In [97]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [98]:
arr1+arr2

array([[3, 3, 3],
       [3, 2, 3],
       [2, 2, 3]])

In [99]:
arr1-arr2

array([[ 1,  1,  1],
       [ 1,  0,  1],
       [ 0,  0, -1]])

In [101]:
arr1*arr2 # indexwise multiplication

array([[2, 2, 2],
       [2, 1, 2],
       [1, 1, 2]])

In [102]:
arr1,arr2

(array([[2, 2, 2],
        [2, 1, 2],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 2]]))

In [103]:
arr1@arr2

array([[6, 6, 8],
       [5, 5, 7],
       [3, 3, 4]])

In [104]:
np.dot(arr1,arr2)

array([[6, 6, 8],
       [5, 5, 7],
       [3, 3, 4]])

In [115]:
a=np.random.randint(2,5,size=(2,3))

In [116]:
a

array([[3, 3, 4],
       [3, 3, 4]])

In [117]:
a.T

array([[3, 3],
       [3, 3],
       [4, 4]])